name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with: # pull changes, replace conn string, build, and restart service
        command: >
          cd /home/Projects/OnlineMenu.Api && 
          git reset --hard && 
          git pull https://${{ secrets.git_hub_username }}:${{ secrets.git_hub_password }}@github.com/OnlineMenu-StartUp/OnlineMenu.Api.git && 
          cd OnlineMenu.Api && 
          sed 's/"RemoteConnection": ""/"RemoteConnection": "${{ secrets.connection_string }}"/g' appsettings.json && 
          dotnet publish --configuration Release && 
          service online-menu-api restart

        host: ${{ secrets.remote_host }}
        username: ${{ secrets.remote_user }}
        privateKey: ${{ secrets.ssh_private_key }}
