name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: String Replace
      uses: shitiomatic/str-replace@v1.0.2
      with:
        # A regular expression of files to include in our find and replace
        include: appsettings.json
        # The string we want to replace
        find: '"RemoteConnection": ""'
        # The new string to replace with
        replace: '"RemoteConnection": "${{secrets.connection_string}}"'
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: ${{ secrets.remote_user }}
        server: ${{ secrets.remote_host }}
        ssh_private_key: '${{ secrets.ssh_private_key }}'
        local_path: './OnlineMenu.Api/OnlineMenu.Api/bin/'
        remote_path: ${{ secrets.target }}
        args: -o ConnectTimeout=5
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo service online-menu-api restart
        host: ${{ secrets.remote_host }}
        username: ${{ secrets.remote_user }}
        privateKey: '${{ secrets.ssh_private_key }}'
