name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with: # pull changes, replace conn string, build, and restart service
        command: >
          cd /home/Projects/OnlineMenu.Api && echo "Went to OnlineMenu.Api solution" && 
          git reset --hard && echo "Removed previous changes" && 
          git pull https://${{ secrets.git_hub_username }}:${{ secrets.git_hub_password }}@github.com/OnlineMenu-StartUp/OnlineMenu.Api.git && echo "Pulled new changes from github" && 
          cd OnlineMenu.Api && echo "Went to OnlineMenu.Api project" && 
          sed 's/"RemoteConnection": ""/"RemoteConnection": "${{ secrets.connection_string }}"/g' appsettings.json -i && echo "Changed the connection string" && 
          sed 's/"JwtKey": ""/"JwtKey": "${{ secrets.jwt_key }}"/g' appsettings.json -i && echo "Changed the JWT key" && 
          dotnet publish --configuration Release && echo "Built the project" && 
          service online-menu-api restart && echo "Restarted project service" 

        host: ${{ secrets.remote_host }}
        username: ${{ secrets.remote_user }}
        privateKey: ${{ secrets.ssh_private_key }}
